// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFnc0yQK4IjzAsziAUYt-0zR37DLOCPi8',
    appId: '1:924520562702:web:c0e6aa439e30b71b633c5f',
    messagingSenderId: '924520562702',
    projectId: 'telerehab-a420e',
    authDomain: 'telerehab-a420e.firebaseapp.com',
    databaseURL:
        'https://telerehab-a420e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'telerehab-a420e.firebasestorage.app',
    measurementId: 'G-TJ8410T0G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTn2pOfy7ZNnQH5-zHz-uD0Q6FyNSVjdo',
    appId: '1:924520562702:android:b17673edbfbaac25633c5f',
    messagingSenderId: '924520562702',
    projectId: 'telerehab-a420e',
    databaseURL:
        'https://telerehab-a420e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'telerehab-a420e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeddHsK1fjZJi_TZFswR-ftjckNMPloQ8',
    appId: '1:924520562702:ios:2f8bfd6d78e5e502633c5f',
    messagingSenderId: '924520562702',
    projectId: 'telerehab-a420e',
    databaseURL:
        'https://telerehab-a420e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'telerehab-a420e.firebasestorage.app',
    iosBundleId: 'com.example.doctorDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeddHsK1fjZJi_TZFswR-ftjckNMPloQ8',
    appId: '1:924520562702:ios:2f8bfd6d78e5e502633c5f',
    messagingSenderId: '924520562702',
    projectId: 'telerehab-a420e',
    databaseURL:
        'https://telerehab-a420e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'telerehab-a420e.firebasestorage.app',
    iosBundleId: 'com.example.doctorDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFnc0yQK4IjzAsziAUYt-0zR37DLOCPi8',
    appId: '1:924520562702:web:0ce9c7a230d0273d633c5f',
    messagingSenderId: '924520562702',
    projectId: 'telerehab-a420e',
    authDomain: 'telerehab-a420e.firebaseapp.com',
    databaseURL:
        'https://telerehab-a420e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'telerehab-a420e.firebasestorage.app',
    measurementId: 'G-169MVCQPMT',
  );
}
